---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/branches/base_job_flags.yml

$inherits:
  from: tasks/branches/base_job_flags.yml

builds:
  aries-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_eng.yml
  flame-kk-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_eng.yml
  linux64:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/opt_linux64.yml
      debug:
        task: tasks/builds/dbg_linux64.yml
  linux64-mulet:
    platforms:
      - Mulet Linux
    types:
      opt:
        task: tasks/builds/mulet_linux.yml

tests:
  gaia-build:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_build_test.yml
  gaia-build-unit:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_build_unit.yml
  gaia-js-integration:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_gaia_js_integration_tests.yml
  gaia-linter:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_linter.yml
  gaia-unit:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_gaia_unit.yml
  gaia-unit-oop:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_gaia_unit_oop.yml
  gaia-ui-test-functional:
    allowed_build_tasks:
      tasks/builds/b2g_flame_kk_eng.yml:
        task: tasks/tests/b2g_e2e_tests.yml
  gaia-ui-test-functional-dsds:
    allowed_build_tasks:
      tasks/builds/b2g_flame_kk_eng.yml:
        task: tasks/tests/b2g_e2e_dsds_tests.yml
  gaia-ui-test-unit:
    allowed_build_tasks:
      tasks/builds/b2g_flame_kk_eng.yml:
        task: tasks/tests/b2g_e2e_api_tests.yml
  mochitest:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_mochitests.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_plain.yml
  mochitest-e10s:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_plain_e10s.yml
  mochitest-a11y:
    allowed_build_tasks:
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_a11y.yml
